# https://stackoverflow.com/questions/34076036/automated-deployment-from-bitbucket-to-iis-on-windows-server
# https://support.atlassian.com/bitbucket-cloud/docs/deploy-using-scp/
pipelines:
  branches: #Branch-specified pipelines
    master:
      - step:
          name: Building the app
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploying the app
          deployment: production
          runs-on: 
            - self.hosted
          script:
            - pipe: atlassian/scp-deploy:latest
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: 'build/*'
                DEBUG: 'true'
      - step:
          name: Running batch script
          cache: docker
          script:
            - pipe: docker://accessefm/bat-script-runner:latest
              variables:
              HOST: $SERVER
              USER: $USER
              PORT: $PORT
              SCRIPT_REMOTE_PATH: $DEPLOY_SCRIPT_PATH
              ARGUMENTS: '$SRC $DEST'
  # default: #Pipelines that doesn't match any other definitions
  # custom: #Pipelines that runs manually