pipeline {
    agent any
    // agent {
    //     node {
    //         label 'your-agent-label'
    //     }
    // }

    stages {
        stage('Build') {
            steps {
                sh 'chmod ./jenkins/scripts/build.sh'
                sh './jenkins/scripts/build.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh 'chmod ./jenkins/scripts/kill.sh'
                sh 'chmod ./jenkins/scripts/deploy.sh'
                sh './jenkins/scripts/kill.sh'
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}