pipeline {
    // agent any
    agent {
        node {
            label 'agent-win-jiajunlee'
        }
    }

    stages {
        stage('Build') {
            steps {
                sh 'chmod +x ./jenkins/scripts/build.sh'
                sh './jenkins/scripts/build.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh 'chmod +x ./jenkins/scripts/kill.sh'
                sh 'chmod +x ./jenkins/scripts/deploy.sh'
                sh './jenkins/scripts/kill.sh'
                sh 'JENKINS_NODE_COOKIE=dontKillMe ./jenkins/scripts/deploy.sh'
            }
        }
    }

    post {
        success {
            mail to: 'lee19@live.cn',
                subject: "Pipeline Succeeded: ${currentBuild.fullDisplayName}",
                body: "Check it out with ${env.BUILD_URL} !"
        }

        failure {
            mail to: 'lee19@live.cn',
                subject: "Pipeline Failed: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL} !"
        }
    }
}